### ISSUE TITLE
개별 페이지에 직접 접근할 수 있으면 좋겠어요

### ISSUE THREAD

**Issue by ahastudio** [CodeSoom/project-react-1-naraekn#67]
`404.html` 파일을 추가하면 (대부분은 그냥 `index.html` 파일을 복사합니다) 개별 페이지에 직접 접근할 때 에러가 발생하지 않게 됩니다.

**Comment by wholemann** [comment]
![Screenshot](https://user-images.githubusercontent.com/47380072/91148318-6d658580-e6f4-11ea-9158-fef4e6e4a054.png)

**Comment by ahastudio** [comment]
404 페이지 디자인: https://github.com/CodeSoom/project-react-1-naraekn/pull/73
